### ISSUE TITLE
Enable dark mode button in docs page

### ISSUE THREAD

**Issue by JaynouOliver** [ultralytics/docs#11]
We are using docs page and it feels tiring to the eyes to look at white pages at night, I can help creating a button got dark mode button in the page to toggle between light and dark mode.

**Comment by glenn-jocher** [comment]
@JaynouOliver yes dark mode is great! We've got you covered here, just click this button to go into dark mode:

<img width="1771" alt="Screenshot 2023-11-03 at 16 09 32" src="https://github.com/ultralytics/docs/assets/26833433/a36f8696-e9c6-4a9c-8012-9da7a7ed7bce">

**Comment by JaynouOliver** [comment]
Thanks
