### ISSUE TITLE
The effect of the IoU threshold for NMS is opposite

### ISSUE THREAD

**Issue by plashchynski** [ultralytics/docs#66]
Files
```
modes/predict/index.html
usage/cfg/index.html
```

have this text: 
```
Intersection Over Union (IoU) threshold for Non-Maximum Suppression (NMS). Higher values result in fewer detections by eliminating overlapping boxes, useful for reducing duplicates.
```

However, in the context of NMS, the effect is opposite. Lower values for the threshold result in fewer detections.

**Comment by plashchynski** [comment]
Moved to https://github.com/ultralytics/ultralytics/issues/9150

**Comment by glenn-jocher** [comment]
@plashchynski hey there! 🌟 Thanks for pointing this out. You're absolutely right, and it seems there's been a mix-up in our documentation. 

For NMS, a lower IoU threshold indeed means it's stricter about what constitutes duplicate detections, therefore reducing the number of boxes kept. A higher IoU threshold is more lenient, allowing more overlap before boxes are considered duplicates.

We appreciate your eagle eyes on this! I'll ensure we update our documentation to correct this misunderstanding. For the most accurate and updated information, always refer to our official docs at https://docs.ultralytics.com.

Thanks for contributing to making our repo better! If you have further insights or questions, feel free to share. 🚀

**Comment by plashchynski** [comment]
Hello @glenn-jocher, please consider my PR to fix it: https://github.com/ultralytics/ultralytics/pull/9151

**Comment by glenn-jocher** [comment]
@plashchynski hey there! 👋 Thanks a bunch for your PR and for diving in to help improve our project. We'll take a look at your changes and get back to you with feedback or merge it if everything checks out. Your contribution is much appreciated! 🚀 Keep an eye on the PR for any updates or requests for changes.
