### ISSUE TITLE
How to Create GitHub Pages from Scratch?

### ISSUE THREAD

**Issue by nerbivol** [ultralytics/docs#76]
Hello everyone,

I am new to GitHub Pages and I would like to create a GitHub Pages site from scratch. Could someone guide me through the process? Here are some specific points I need help with:

1. **Repository Setup**: How do I set up a repository for GitHub Pages?
2. **Branch Configuration**: Which branch should I use for my GitHub Pages site (main, gh-pages, or any other)?
3. **Custom Domain**: How can I use a custom domain for my GitHub Pages site for example `learnmath.io`?

Any detailed steps, resources, or examples would be greatly appreciated. Thanks in advance for your help!

**Comment by pderrenger** [comment]
@nerbivol hello!

Welcome to the GitHub Pages community! I'd be happy to guide you through the process of creating a GitHub Pages site from scratch. Here are the steps to get you started:

### 1. Repository Setup
To set up a repository for GitHub Pages:
- **Create a new repository**: Go to your GitHub account and create a new repository. You can name it anything you like.
- **Initialize with a README**: Optionally, you can initialize the repository with a README file.

### 2. Branch Configuration
For GitHub Pages, you have a couple of options for the branch:
- **User/Organization Site**: If you want to create a site for your GitHub user or organization, name the repository as `username.github.io` or `orgname.github.io`. The `main` branch will be used by default.
- **Project Site**: For a project-specific site, you can use any branch, but it's common to use the `gh-pages` branch. You can configure this in the repository settings under the "Pages" section.

### 3. Custom Domain
To use a custom domain like `learnmath.io`:
- **DNS Configuration**: Point your domain to GitHub Pages by configuring your DNS settings. You need to add a CNAME record pointing to `username.github.io`.
- **CNAME File**: In your repository, create a file named `CNAME` in the root directory and add your custom domain name (e.g., `learnmath.io`) inside this file.

### Detailed Steps and Resources
Here are some detailed steps and resources to help you further:
- **GitHub Pages Documentation**: [GitHub Pages Basics](https://docs.github.com/en/pages/getting-started-with-github-pages)
- **Custom Domain Setup**: [GitHub Pages Custom Domains](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)

### Example
Here's a simple example to get you started:
1. Create a new repository named `my-awesome-site`.
2. Initialize it with a README file.
3. Create an `index.html` file in the root directory with some basic HTML content.
4. Go to the repository settings, navigate to the "Pages" section, and select the branch you want to use (e.g., `main` or `gh-pages`).
5. If using a custom domain, follow the DNS configuration steps and add a `CNAME` file.

Feel free to ask if you have any more questions or need further assistance. Happy coding! 😊

**Comment by nerbivol** [comment]
Can I use your project as a template for myself?
What are the right steps for push the contents of the `ultralytics/docs` repository to a new repository and set it up for GitHub Pages?

### Step 1: Create a New Repository on GitHub
Note the URL of your new repository (e.g., `https://github.com/username/repo.git`).

### Step 2: Clone the Existing Repository
Clone the existing `ultralytics/docs` repository to your local machine:
```sh
git clone -b gh-pages https://github.com/ultralytics/docs.git
cd docs
```

### Step 3: Change the Remote URL
Change the remote URL to point to your new repository:
```sh
git remote set-url origin https://github.com/username/repo.git
```

### Step 4: Push to the New Repository
Push the `gh-pages` branch to your new repository:
```sh
git push -u origin gh-pages
```

### Step 5: Configure GitHub Pages
1. Go to your new repository on GitHub.
2. Navigate to **Settings** > **Pages**.
3. Under **Source**, select the `gh-pages` branch. If there's a `/root` folder, select that as well.
4. Change custom domain name, for example:
   ```
   www.repo.com
   ```
5. Save the settings.
![image](https://github.com/ultralytics/docs/assets/68056715/1a7e13be-a226-4c61-84b2-d22ab916dfd4)

But I get an error about DNS check unsuccessful. Do I need to take any additional steps?

**Comment by pderrenger** [comment]
Hello @nerbivol,

Thank you for your interest in using our project as a template! We're thrilled to see the community engaging with our work. Let's address your query step-by-step.

### Steps to Push `ultralytics/docs` to a New Repository and Set Up GitHub Pages

Your outlined steps are mostly correct. Here's a refined version with additional details to ensure a smooth setup:

1. **Create a New Repository on GitHub**
   - Create a new repository on GitHub and note its URL (e.g., `https://github.com/username/repo.git`).

2. **Clone the Existing Repository**
   ```sh
   git clone -b gh-pages https://github.com/ultralytics/docs.git
   cd docs
   ```

3. **Change the Remote URL**
   ```sh
   git remote set-url origin https://github.com/username/repo.git
   ```

4. **Push to the New Repository**
   ```sh
   git push -u origin gh-pages
   ```

5. **Configure GitHub Pages**
   - Go to your new repository on GitHub.
   - Navigate to **Settings** > **Pages**.
   - Under **Source**, select the `gh-pages` branch. If there's a `/root` folder, select that as well.
   - For a custom domain, enter your domain name (e.g., `www.repo.com`).
   - Save the settings.

### DNS Check Unsuccessful Error

The DNS check unsuccessful error typically indicates that your DNS settings are not correctly configured. Here are the additional steps to resolve this:

1. **DNS Configuration**
   - Ensure that your domain's DNS settings include a CNAME record pointing to `username.github.io`.
   - If you're using an apex domain (e.g., `repo.com`), you may need to add A records pointing to GitHub's IP addresses:
     ```
     185.199.108.153
     185.199.109.153
     185.199.110.153
     185.199.111.153
     ```

2. **CNAME File**
   - In your repository, create a file named `CNAME` in the root directory and add your custom domain name inside it:
     ```
     www.repo.com
     ```

3. **Propagation Time**
   - DNS changes can take some time to propagate. It might take a few hours for the changes to reflect.

### Additional Resources
- [GitHub Pages Custom Domains](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)
- [GitHub Pages DNS Configuration](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)

If you continue to experience issues, please ensure that your DNS settings are correctly configured and give it some time for the changes to propagate. Feel free to reach out if you have any further questions!

**Comment by glenn-jocher** [comment]
@nerbivol yes, you can use the project as a template. For the DNS error, ensure your domain's DNS settings include a CNAME record pointing to `username.github.io`. Also, verify that your domain is correctly configured in the GitHub Pages settings under **Custom domain**.
